[workspace]
members = [
    "libs",
    "setup/trusted-setup",
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.6.0", package = "icicle-runtime" }
icicle-core = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.6.0", package = "icicle-core" }
icicle-bls12-381 = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.6.0", package = "icicle-bls12-381"}
libs = { path = "libs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.4"
num-bigint = "0.4"
num-traits = "0.2"
rayon = "1.7"